# permissions for end users to edit jupytergateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupytergateway-editor-role
rules:
- apiGroups:
  - kubeflow.tkestack.io.my.domain
  resources:
  - jupytergateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.tkestack.io.my.domain
  resources:
  - jupytergateways/status
  verbs:
  - get
