# permissions for end users to edit jupyternotebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyternotebook-editor-role
rules:
- apiGroups:
  - kubeflow.tkestack.io.my.domain
  resources:
  - jupyternotebooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubeflow.tkestack.io.my.domain
  resources:
  - jupyternotebooks/status
  verbs:
  - get
