# permissions for end users to view jupyternotebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyternotebook-viewer-role
rules:
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyternotebooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kubeflow.tkestack.io
  resources:
  - jupyternotebooks/status
  verbs:
  - get
