name: CI with Eco-CI

on: [push, pull_request]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.17" # Adjust the version as needed

      - name: Install Dependencies
        run: go mod tidy

      - name: Post-Setup Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: "Setup"

      - name: Build Go Application
        run: go build -o main main.go

      - name: Run Script
        run: ./main

      - name: Execution Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: get-measurement
          label: "Script Execution"

      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
