name: ci.yml
on:
  push:
    branches:
      - master

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: start-measurement
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.17'
      - name: Install Dependencies
        run: go mod tidy
      - id: measurement-5
        name: Record Measurement After Install Dependencies
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install Dependencies
          task: get-measurement
      - name: Post-Setup Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          label: Setup
          task: get-measurement
      - name: Build Go Application
        run: go build -o main main.go
      - id: measurement-8
        name: Record Measurement After Build Go Application
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build Go Application
          task: get-measurement
      - name: Run Script
        run: ./main
      - id: measurement-10
        name: Record Measurement After Run Script
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Run Script
          task: get-measurement
      - name: Execution Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          label: Script Execution
          task: get-measurement
      - name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          task: display-results
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption.json
